docs_dir: doc/book
site_dir: doc/html
nav:
    - index.md
    - Reference:
        - Translation: translation.md
        - 'View Helpers': view-helpers.md
        - Filters: filters.md
        - Validators: validators.md
site_name: laminas-i18n
site_description: Laminas\I18n
repo_url: 'https://github.com/laminas/laminas-i18n'
